project:
  type: book

book:
  title: "iMOD Suite Tutorial"
  chapters:
    - index.qmd
    - tutorial.qmd
    - tutorial_Abbeyfeale.qmd

format:
  pdf:
    documentclass: scrreprt
    top-level-division: chapter
